name: Dataplane Python Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose -f tests/docker-compose.yaml up --build -d

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -s
        env: 
          SHAREPOINT_HOST: ${{ secrets.SHAREPOINT_HOST }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
          REDIS_HOST: "localhost"
          S3_HOST: "http://localhost:9000"